config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  get '/about-us', to: "pages#about_us"
  get '/sign-up', to: "users#new"
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
  resources :blogs
  resources :categories
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_and_belongs_to_many :categories
  belongs_to :user

  validates :title, presence: true, length: {minimum: 2, maximum: 100}
  validates :content, presence: true, length: {minimum: 2, maximum: 200}
  
  validate :image_path_exists 

  def image_path_exists
    require 'open-uri'

    begin
      #is the URL valid?
      #if thrown an exception, rescue will execute
      path = URI.open(image_path)
      #does the response have a content type of image?
      #path.content_type.starts_with?("image")
      errors.add(:image_path, "does not contain image content") and return unless path.content_type.starts_with?("image")

    rescue
      errors.add(:image_path, "invalid url")

    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :blogs


  
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, :email, presence: true, uniqueness: true, length: {minimum: 3, maximum: 25 }
  validates :email, format: {with: URI::MailTo::EMAIL_REGEXP}
  has_secure_password

  has_many :blogs

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def require_user
    #if user is a guest, then redirect to Login page
    if guest?
      flash[:notice] = "You must login to view blogs"
      redirect_to login_path
    end
  end

  def already_signed_in? 
    if !guest?
      flash[:notice] = "User already signed in"
      redirect_to blogs_path
    end
  end

  def guest?
    !helpers.logged_in?
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show]
  before_action :require_same_blogger, only: [:destroy]

  #GET - show all blogs
  def index
    @blogs = Blog.all
  end

  #GET - show a specific blog
  def show
  end

  #GET - request page to create a new blog with form to create a blog
  def new
    @blog = Blog.new 
  end

  #POST - actually create the blog
  def create
    # @blog = Blog.new(blog_params)
    @blog = helpers.current_user.blogs.new(blog_params)

    if @blog.save
      flash[:notice] = "Blog successfully saved"
      redirect_to blogs_path
    else 
      flash[:notice] = "There was an error creating a blog"
      render :new, status: :unprocessable_entity
    end
  end

  #GET - edit blog (the edit screen, not the act of saving the update)
  def edit
  end

  #PATCH? Update existing blog
  def update 
    if @blog.update(blog_params)
      redirect_to blogs_path
    else 
      flash[:notice] = "There was an error updating blog"
      render :edit, status: :unprocessable_entity
    end 
  end

  def destroy 
    @blog.destroy
    redirect_to blogs_path
  end

  private 
  
  def set_blog
    @blog = Blog.find(params[:id])
  end

  def require_same_blogger
    if helpers.current_user != @blog.user 
      flash[:notice] = "Unauthorized action attempt!" 
      redirect_to helpers.current_user
    end
  end
  
  def blog_params
    params.require(:blog).permit(:title, :content, :image_path, category_ids: [])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about_us
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :already_signed_in?, except: [:destroy]
  #GET - Login Page
  def new

  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id 
      flash[:notice] = "Login successful"
      redirect_to blogs_path
    else
      flash[:notice] = "Login failed"
      render :new, status: :unprocessable_entity
    end

    def destroy
      session[:user_id] = nil
      flash[:notice] = "Logout successful"
      redirect_to login_path
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :already_signed_in?, only: [:new, :create]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "Account created successfully"
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @user = User.find(params[:id])

  end

  private
  def user_params 
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog) do |form| %>
  <% if @blog.errors.any? %>
    <% @blog.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>
  <div>
    <%= form.label :image_path %>
    <%= form.text_field :image_path %>
  </div>
  <div>
    <%= form.label :category_ids %>
    <%= form.collection_select(:category_ids, Category.all, :id, :name, {}, {multiple: true}) %>
  </div>
  <%= form.submit %>
<% end %>

app/views/blogs/edit.html.erb
<h1>Edit <%= @blog.title %><h1>

<%= render "form" %>

app/views/blogs/index.html.erb
<h1>Blogs</h1>

<% @blogs.each do |blog| %>
  <h2><%= blog.title %></h2>
  <p>Content: <%= blog.content %></p>
  
  <div>
    <%= link_to blog_path(blog) do %>
      <%= image_tag blog.image_path, style: "border: 1px solid black" %>
    <% end %>
  </div>
<% end %>

app/views/blogs/new.html.erb
<h1>Create a Blog</h1>

<%= render "form" %>

app/views/blogs/show.html.erb
<h1><%= @blog.title %></h1>

<% if @blog.user %>
  <div><%= link_to "By: #{@blog.user.username}", @blog.user  %></div>

<% end %> 

<p> <%= @blog.content %> </p>
<div>
  <%= image_tag @blog.image_path, style: "border: 1px solid black" %>
</div>
<div>
  <% @blog.categories.each do |category| %>
    <b style="margin-right: 6px"><%= category.name %></b>
  <% end %>
</div>



<% if current_user == @blog.user %>
  <%= link_to "Edit", edit_blog_path(@blog) %>
  <%= button_to "Delete", @blog, method: :delete %>
<% end %>

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<% @category.blogs.each do |blog| %>
  <h2>
    <%= link_to blog_path(blog) do %>
      <%= blog.title %>
    <% end %>
  </h2>
<% end %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogalong</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>

    <%= render 'shared/nav' %>

    <%= yield %>
  </body>
</html>

app/views/pages/about_us.html.erb
<h1>Pages#about_us</h1>
<p>Find me in app/views/pages/about_us.html.erb</p>

app/views/pages/home.html.erb
<h1 class="text-center">Discovery a New Adventure of Blogging</h1>
<p class="text-center">Click below to start reading, or add your own!</p>

<div class="container">
  <div class="row">
    <% Blog.limit(6).each do |blog| %>
      <div class="col-xs-12 col-md-6 col-lg-4">
        <div class="card" style="width: 100%; margin-bottom: 1rem">
          <%= image_tag blog.image_path, class: "card-img-top" %>
          <div class="card-body">
            <h5 class="card-title"><%= blog.title %></h5>
            <p class="card-text"><%= blog.content.slice(0, 30) %></p>
            <%= link_to "Continue Reading...", blog, class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to 'Blogalong', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <li><%= link_to 'About Us', about_us_path, class: "nav-link" %></li>
        </li>

        <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Explore Blogs:
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Blogs', blogs_path, class: "dropdown-item" %></li>
            <li><%= link_to 'My Blogs', user_path(current_user), class: "dropdown-item" %></li>
            <li><%= link_to 'Create a new Blog', new_blog_path, class: "dropdown-item" %></li>
          </ul>
        </li>
        <li class="nav-item">
          <%= link_to 'Categories', categories_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Logout', logout_path, data: {"turbo-method": :delete}, class: "nav-link" %>
        </li>

        <% else %>
          <li class="nav-item">
            <%= link_to 'Login', login_path, class: "nav-link"  %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up', sign_up_path, class: "nav-link"  %>
          </li>

        <% end %>
        
      </ul>
    </div>
  </div>
</nav>

app/views/users/new.html.erb
<h1> Sign Up </h1>
<% if @user.errors.any? %>
  <div style="color: red">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

    <ul>
      <% @user.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user) do |form| %>
  <div>
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <%= form.submit "Sign Up" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %> Blogs </h1>

<% @user.blogs.each do |blog| %>
  <h2><%= blog.title %></h2>
  <p>Content: <%= blog.content %></p>
  
  <div>
    <%= link_to blog_path(blog) do %>
      <%= image_tag blog.image_path, style: "border: 1px solid black" %>
    <% end %>
  </div>
<% end %>